domain: "poisson.development.run"
ravenImageTag: latest
licenseFilePath: misc/license.json
packageFilePath: misc/pack.zip
storageSize: 5Gi
ingressClassName: nginx
# RavenDB nodes
# todo: allow to define more than 3 nodes with custom tags etc.
nodes:
  - nodeTag: "A"
    publicTcpPort: 38887
  - nodeTag: "B"
    publicTcpPort: 38888
  - nodeTag: "C"
    publicTcpPort: 38889
environment:
  MY_ENV: 'amongus'
