ingress:
  host: [ localhost ]

domain: "poisson.development.run"
ravenVersion: latest
licenseFileName: misc/license.json

persistence:
  storage: 2G

# Instances
nodes:
- nodeTag: "A"
  nodeIndex: 0
- nodeTag: "B"
  nodeIndex: 1
- nodeTag: "C"
  nodeIndex: 2
  