domain: "poisson.development.run"
ravenVersion: latest
licenseFilePath: misc/license.json
packageFilePath: misc/pack.zip
storageSize: 5Gi

# RavenDB nodes
nodes:
  - nodeTag: "A"
    publicTcpPort: 38887
  - nodeTag: "B"
    publicTcpPort: 38888
  - nodeTag: "C"
    publicTcpPort: 38889
  