{{- $shortname := include "ravendb.name" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ravendb.fullname" . }} 
  labels:
    app.kubernetes.io/name: {{ include "ravendb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ingressClassName: nginx
  rules:
    - host: "a.{{.Values.domain}}"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service: 
                name: {{ $shortname }}-0
                port:
                  number: 80
            
    - host: "b.{{.Values.domain}}"
      http:
        paths:
          - pathType: Prefix
            path: / 
            backend:
              service: 
                name: {{ $shortname }}-1
                port:
                  number: 80

    - host: "c.{{.Values.domain}}"
      http:
        paths:
          - pathType: Prefix
            path: / 
            backend:
              service: 
                name: {{ $shortname }}-2
                port:
                  number: 80
    - host: "a-tcp.{{.Values.domain}}"
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /
            backend:
              service: 
                name: {{ $shortname }}-0
                port:
                  number: 38888
            
    - host: "b-tcp.{{.Values.domain}}"
      http:
        paths:
          - pathType: ImplementationSpecific
            path: / 
            backend:
              service: 
                name: {{ $shortname }}-1
                port:
                  number: 38888

    - host: "c-tcp.{{.Values.domain}}"
      http:
        paths:
          - pathType: ImplementationSpecific
            path: / 
            backend:
              service: 
                name: {{ $shortname }}-2
                port:
                  number: 38888
# todo: make dictionary and assign numbers to dns node tags {1:"a", 2:"b", 3:"c" ...}