apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modify-secrets
  namespace: ravendb
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - patch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: ravendb
  name: modify-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modify-secrets
  namespace: ravendb
subjects:
  - kind: ServiceAccount
    name: modify-secrets
    namespace: ravendb
roleRef:
  kind: Role
  name: modify-secrets
  apiGroup: rbac.authorization.k8s.io
