apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modify-config
  namespace: ravendb
rules:
  - apiGroups: [""]
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - patch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: ravendb
  name: modify-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modify-config
  namespace: ravendb
subjects:
  - kind: ServiceAccount
    name: modify-config
    namespace: ravendb
roleRef:
  kind: Role
  name: modify-config
  apiGroup: rbac.authorization.k8s.io
