{{- $shortname := include "ravendb.name" . -}}

{{- range .Values.nodes }}
apiVersion: v1
kind: Service
metadata:
  name: "ravendb-{{.nodeIndex}}"
  labels:
    app: ravendb
spec:
  ports:
  - port: 443
    name: https
  - port: 38888
    protocol: TCP
    name: tcp
  selector:
    nodeTag: {{.nodeTag}}
---
{{- end }}