{{- $shortname := include "ravendb.name" . -}}

# {{- range .Values.nodesTags }}
# apiVersion: v1
# kind: Service
# metadata:
#   name: "{{$shortname}}-{{.}}"
#   labels:
#     app: "{{$shortname}}"
# spec:
#   ports:
#   - port: 8080
#     name: http
#   - port: 38888
#     name: tcp
#   selector:
#     nodeTag: "{{.}}"
# {{- end }}

apiVersion: v1
kind: Service
metadata:
  name: ravendb-0
  labels:
    app: ravendb
spec:
  ports:
  - port: 80
    name: http
  - port: 38888
    protocol: TCP
    name: tcp
  selector:
    nodeTag: "A"
---
apiVersion: v1
kind: Service
metadata:
  name: ravendb-1
  labels:
    app: ravendb
spec:
  ports:
  - port: 80
    name: http
  - port: 38888
    name: tcp
    protocol: TCP
  selector:
    nodeTag: "B"
---
apiVersion: v1
kind: Service
metadata:
  name: ravendb-2
  labels:
    app: ravendb
spec:
  ports:
  - port: 80
    name: http
  - port: 38888
    protocol: TCP
    name: tcp
  selector:
    nodeTag: "C"