apiVersion: v1
kind: Service
metadata:
  name: {{ include "ravendb.name" . }}
  labels:
    app: {{ include "ravendb.name" . }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: http
  selector:
    app: {{ include "ravendb.name" . }}
