apiVersion: v1
kind: Service
metadata:
  name: {{ include "ravendb.name" . }}-0
  labels:
    app: {{ include "ravendb.name" . }}
spec:
  ports:
  - port: 8080
    name: http
  - port: 38888
    name: tcp
  selector:
    app: {{ include "ravendb.name" . }}
    statefulset.kubernetes.io/pod-name: {{ include "ravendb.fullname" . }}-0
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ravendb.name" . }}-1
  labels:
    app: {{ include "ravendb.name" . }}
spec:
  ports:
  - port: 8080
    name: http
  - port: 38888
    name: tcp
  selector:
    app: {{ include "ravendb.name" . }}
    statefulset.kubernetes.io/pod-name: {{ include "ravendb.fullname" . }}-1
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ravendb.name" . }}-2
  labels:
    app: {{ include "ravendb.name" . }}
spec:
  ports:
  - port: 8080
    name: http
  - port: 38888
    name: tcp
  selector:
    app: {{ include "ravendb.name" . }}
    statefulset.kubernetes.io/pod-name: {{ include "ravendb.fullname" . }}-2
    