{{- $shortname := include "ravendb.name" . -}}
{{- $fullname := include "ravendb.fullname" . -}}

{{- range .Values.nodeIndexes }}
  apiVersion: v1
  kind: Service
  metadata:
    name: "{{$.shortname}}-{{.}}"
    labels:
      app: {{ $.shortname }}
  spec:
    ports:
    - port: 8080
      name: http
    - port: 38888
      name: tcp
    selector:
      app: {{ $.shortname }}
      name: "{{$.fullname}}-0"
{{- end }}