{{- $shortname := include "ravendb.name" . -}}

apiVersion: v1
kind: Pod
metadata:
  name: "{{$shortname}}-sidecar"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    app: {{$shortname}}
spec:
  restartPolicy: OnFailure
  volumes:
    - name: {{$shortname}}-scripts
      configMap:
        name: {{$shortname}}-scripts
    - name: {{$shortname}}-pack
      secret:
        secretName: {{$shortname}}-pack
  containers:
  - name: main
    image: "ubuntu:latest" # todo: use more lightweight distro like alpine with bash
    command: ["/bin/bash"]
    args: ["/usr/scripts/create-cluster.sh"]
    volumeMounts:
      - name: {{$shortname}}-scripts
        mountPath: /usr/scripts
      - name: {{$shortname}}-pack
        mountPath: /usr/ravendb
