apiVersion: v1
kind: Pod
metadata:
  name: "ravendb-cluster-creator"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    app: ravendb
spec:
  restartPolicy: OnFailure
  volumes:
    - name: ravendb-scripts
      configMap:
        name: ravendb-scripts
    - name: ravendb-pack
      secret:
        secretName: ravendb-pack
  containers:
  - name: main
    image: "ubuntu:latest" # todo: use more lightweight distro like alpine with bash
    command: ["/bin/bash"]
    args: ["/ravendb/scripts/create-cluster.sh"]
    volumeMounts:
      - name: ravendb-scripts
        mountPath: /ravendb/scripts
      - name: ravendb-pack
        mountPath: /usr/ravendb
