{{- $shortname := include "ravendb.name" . -}}

{{- range .Values.nodes }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{$shortname}}-{{.nodeTag | lower }}"
  annotations: 
    ingress.kubernetes.io/ssl-passthrough: "true"
  labels:
    heritage: {{$.Release.Service | quote }}
    release: {{$.Release.Name | quote }}
    chart: "{{$.Chart.Name}}-{{$.Chart.Version}}"
    app: ravendb
    nodeTag: "{{.nodeTag}}"
spec:
  selector:
    matchLabels:
      nodeTag: "{{.nodeTag}}"
  serviceName: "{{$shortname}}-{{.nodeTag | lower }}"
  replicas: 1
  template:
    metadata:
      labels:
        nodeTag: "{{.nodeTag}}"
    spec:
      dnsPolicy: Default
      containers:
      - name: {{ $.Chart.Name }}
        image: "ravendb/ravendb:{{$.Values.ravenVersion}}"
        ports:
        - containerPort: 443
          name: https
        - containerPort: 38888
          name: tcp
          protocol: TCP
        volumeMounts:
          - name: "{{$shortname}}"
            mountPath: /opt/RavenDB/Server/RavenData
        env:
        - name: RAVEN_Setup_Mode
          value: 'NONE'
        - name: RAVEN_License_Eula_Accepted
          value: 'true'
        - name: RAVEN_License
          value: {{ $.Files.Get $.Values.licenseFilePath | toPrettyJson }}
        - name: RAVEN_ARGS
          value: --Security.UnsecuredAccessAllowed=PublicNetwork --Security.Certificate.Load.Exec=/usr/scripts/get-server-cert.sh --Security.Certificate.Load.Exec.Arguments=/usr/scripts/get-server-cert.sh --Security.Certificate.Exec.TimeoutInSec=60
        - name: RAVEN_ServerUrl
          value: "https://0.0.0.0:443"
        - name: RAVEN_ServerUrl_Tcp
          value: "tcp://0.0.0.0:38888"
        - name: RAVEN_PublicServerUrl
          value: "https://{{ .nodeTag | lower }}.{{$.Values.domain}}:443"
        - name: RAVEN_PublicServerUrl_Tcp
          value: "tcp://{{ .nodeTag | lower }}-tcp.{{$.Values.domain}}:{{.publicTcpPort}}"
        volumeMounts:
          - name: {{$shortname}}-scripts
            mountPath: /usr/scripts
          - name: {{$shortname}}-pack
            mountPath: /usr/ravendb
      volumes:
        - name: {{$shortname}}-scripts
          configMap:
            name: {{$shortname}}
            defaultMode: 0700
        - name: {{$shortname}}-pack
          secret:
            secretName: {{$shortname}}-pack
  volumeClaimTemplates:
    - metadata:
        name: {{$shortname}}
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ $.Values.storageSize }}
---
{{- end }}