{{- $shortname := include "ravendb.name" . -}}

{{- range .Values.nodes }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{$shortname}}-{{.nodeIndex}}"
  labels:
    heritage: {{$.Release.Service | quote }}
    release: {{$.Release.Name | quote }}
    chart: "{{$.Chart.Name}}-{{$.Chart.Version}}"
    app: ravendb
    nodeTag: "{{.nodeTag}}"
spec:
  selector:
    matchLabels:
      nodeTag: "{{.nodeTag}}"
  serviceName: "{{$shortname}}-{{.nodeIndex}}"
  replicas: 1
  template:
    metadata:
      labels:
        nodeTag: "{{.nodeTag}}"
    spec:
      dnsPolicy: Default
      containers:
      - name: {{ $.Chart.Name }}
        image: "ravendb/ravendb:{{$.Values.ravenVersion}}"
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 38888
          name: tcp
          protocol: TCP
        volumeMounts:
          - name: "{{$shortname}}"
            mountPath: /opt/RavenDB/Server/RavenData
        env:
        - name: RAVEN_Setup_Mode
          value: 'NONE'
        - name: RAVEN_License_Eula_Accepted
          value: 'true'
        - name: RAVEN_License
          value: {{ $.Files.Get "misc/license.json" | toPrettyJson }}
        - name: RAVEN_ARGS
          value: --Security.UnsecuredAccessAllowed=PublicNetwork
        - name: RAVEN_ServerUrl
          value: "http://0.0.0.0:80"
        - name: RAVEN_ServerUrl_Tcp
          value: "tcp://0.0.0.0:38888"
        - name: RAVEN_PublicServerUrl
          value: "http://a.{{$.Values.domain}}:80"
        - name: RAVEN_PublicServerUrl_Tcp
          value: "tcp://a-tcp.{{$.Values.domain}}:{{.publicTcpPort}}"
  volumeClaimTemplates:
    - metadata:
        name: {{$shortname}}
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
{{- end }}
