{{- range .Values.nodes }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "ravendb-{{.nodeTag | lower }}"
  annotations: 
    ingress.kubernetes.io/ssl-passthrough: "true"
  labels:
    heritage: {{$.Release.Service | quote }}
    release: {{$.Release.Name | quote }}
    chart: "{{$.Chart.Name}}-{{$.Chart.Version}}"
    app: ravendb
    nodeTag: "{{.nodeTag}}"
spec:
  selector:
    matchLabels:
      nodeTag: "{{.nodeTag}}"
  serviceName: "ravendb-{{.nodeTag | lower }}"
  replicas: 1
  template:
    metadata:
      labels:
        nodeTag: "{{.nodeTag}}"
    spec:
      dnsPolicy: Default
      serviceAccountName: modify-secrets
      initContainers:
      - name: "{{$.Chart.Name}}-init"
        image: "ubuntu:latest" # todo: use more lightweight distro like alpine with bash
        command: ["/bin/bash"]
        args: ["/ravendb/scripts/set-cert.sh"]
        volumeMounts:
          - name: ravendb-scripts
            mountPath: /ravendb/scripts
          - name: ravendb-pack
            mountPath: /usr/ravendb
          - name: ravendb-certs
            mountPath: /ravendb/certs
            readOnly: false
      containers:
      - name: ravendb-container
        image: "ravendb/ravendb:{{$.Values.ravenImageTag}}"
        ports:
        - containerPort: 443
          name: https
        - containerPort: 38888
          name: tcp
          protocol: TCP
        env:
        - name: RAVEN_License_Eula_Accepted
          value: 'true'
        - name: RAVEN_License
          value: {{ $.Files.Get $.Values.licenseFilePath | toPrettyJson }}
        - name: RAVEN_Security_Certificate_LetsEncrypt_Email
          value: {{$.Values.letsEncryptEmail}}
        - name: RAVEN_Setup_Mode
          value: "LetsEncrypt"
        # - name: RAVEN_AcmeUrl
        #   value: "https://acme-staging-v02.api.letsencrypt.org/directory"
        - name: RAVEN_ARGS
          value: --Security.UnsecuredAccessAllowed=PublicNetwork --Security.Certificate.Load.Exec=/ravendb/scripts/get-server-cert.sh --Security.Certificate.Exec.TimeoutInSec=60 --Security.Certificate.Change.Exec=/ravendb/scripts/update-cert.sh --Security.Certificate.Renew.Exec=/ravendb/scripts/renew-cert.sh
        - name: RAVEN_ServerUrl
          value: "https://0.0.0.0:443"
        - name: RAVEN_ServerUrl_Tcp
          value: "tcp://0.0.0.0:38888"
        - name: RAVEN_PublicServerUrl
          value: "https://{{ .nodeTag | lower }}.{{$.Values.domain}}:443"
        - name: RAVEN_PublicServerUrl_Tcp
          value: "tcp://{{ .nodeTag | lower }}-tcp.{{$.Values.domain}}:{{.publicTcpPort}}"
        {{- range $key, $val := $.Values.environment }}
        - name: {{ $key }}
          value: {{ $val }}
        {{ end -}}
        volumeMounts:
          - name: ravendb-scripts
            mountPath: /ravendb/scripts
          - name: ravendb-pack
            mountPath: /usr/ravendb
          - name: ravendb-certs
            mountPath: /ravendb/certs
          - name: "ravendb"
            mountPath: /opt/RavenDB/Server/RavenData
      volumes:
        - name: ravendb-scripts
          configMap:
            name: ravendb-scripts
            defaultMode: 0700
        - name: ravendb-pack
          secret:
            secretName: ravendb-pack
        - name: ravendb-certs
          secret:
            secretName: ravendb-certs
  volumeClaimTemplates:
    - metadata:
        name: ravendb
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ $.Values.storageSize }}
---
{{- end }}
